import type { Metadata } from "next";

import "../styles/globals.css";
import "../styles/scroll-bar.css";
import { ReactQueryClientProvider } from "@/utils/providers/react-query-provider";
import ContextProvider from "@/utils/providers/context-provider";
import { AvatarImage, Avatar, AvatarFallback } from "@/components/ui/avatar";
import Link from "next/link";
import MainHeader from "@/components/header/main-header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <ContextProvider>
            <main className="h-screen flex flex-col">
              <MainHeader />
              <Suspense>{children}</Suspense>
            </main>
          </ContextProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
